=begin
#Sources

#Sources

The version of the OpenAPI document: 3.1.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.1

=end

module SourcesApiClient
  VERSION = '1.0.0'
end
