=begin
#Sources

#Sources

OpenAPI spec version: 0.1.0
Contact: you@your-company.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

module SourcesApiClient
  VERSION = '1.0.0'
end
