=begin
#Sources

#Sources

The version of the OpenAPI document: 3.1.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SourcesApiClient::BulkCreatePayloadSources
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BulkCreatePayloadSources' do
  before do
    # run before each test
    @instance = SourcesApiClient::BulkCreatePayloadSources.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BulkCreatePayloadSources' do
    it 'should create an instance of BulkCreatePayloadSources' do
      expect(@instance).to be_instance_of(SourcesApiClient::BulkCreatePayloadSources)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "source_type_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["amazon", "azure", "ansible-tower", "openshift", "satellite", "google"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.source_type_name = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "source_ref"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "source_type_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "app_creation_workflow"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["manual_configuration", "account_authorization"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.app_creation_workflow = value }.not_to raise_error
      # end
    end
  end

end
