=begin
#Sources

#Sources

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

# Common files
require 'sources-api-client/api_client'
require 'sources-api-client/api_error'
require 'sources-api-client/version'
require 'sources-api-client/configuration'

# Models
require 'sources-api-client/models/application'
require 'sources-api-client/models/application_type'
require 'sources-api-client/models/application_types_collection'
require 'sources-api-client/models/applications_collection'
require 'sources-api-client/models/authentication'
require 'sources-api-client/models/authentications_collection'
require 'sources-api-client/models/collection_links'
require 'sources-api-client/models/collection_metadata'
require 'sources-api-client/models/endpoint'
require 'sources-api-client/models/endpoints_collection'
require 'sources-api-client/models/order_parameters'
require 'sources-api-client/models/source'
require 'sources-api-client/models/source_type'
require 'sources-api-client/models/source_types_collection'
require 'sources-api-client/models/sources_collection'
require 'sources-api-client/models/tagging'
require 'sources-api-client/models/tenant'

# APIs
require 'sources-api-client/api/default_api'

module SourcesApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   SourcesApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
